pw_progres_sies:
    resource: "@PWProgresSiesBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@PWUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@PWUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@PWUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@PWUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@PWUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

coresphere_console:
    resource: .
    type: extra
